# Generated by Django 4.2.4 on 2023-08-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangoAPP", "0002_planta_alter_userprofile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planta",
            name="imagen_blob",
        ),
        migrations.AddField(
            model_name="planta",
            name="imagen_base64",
            field=models.TextField(default=""),
        ),
    ]
