# Generated by Django 4.2.4 on 2023-09-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangoAPP", "0003_remove_planta_imagen_blob_planta_imagen_base64"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.TextField(default=""),
        ),
    ]
