# Generated by Django 4.2.4 on 2023-09-01 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mangoAPP", "0005_userprofile_is_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="is_admin",
            new_name="userAdmin",
        ),
    ]
