# Generated by Django 4.2.4 on 2023-09-04 03:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mangoAPP", "0007_propietario_remove_planta_fase_remove_planta_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleados",
            name="Id_usuario",
        ),
        migrations.RemoveField(
            model_name="empleados",
            name="nombres",
        ),
    ]
