# Generated by Django 4.2.4 on 2023-09-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangoAPP", "0008_remove_empleados_id_usuario_remove_empleados_nombres"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleados",
            name="nombres",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
