# Generated by Django 4.2.4 on 2023-09-05 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mangoAPP", "0009_empleados_nombres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleados",
            name="Id_vivero",
        ),
        migrations.RemoveField(
            model_name="viveros",
            name="Id_propietario",
        ),
        migrations.AddField(
            model_name="empleados",
            name="contraseña",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empleados",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mangoAPP.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="viveros",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mangoAPP.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tratamientos",
            name="Id_enfermedad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mangoAPP.enfermedad"
            ),
        ),
        migrations.DeleteModel(
            name="Propietario",
        ),
    ]
