# Generated by Django 4.2.4 on 2023-09-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangoAPP", "0012_viveros_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleados",
            name="usuario",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
