# Generated by Django 4.2.4 on 2023-09-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mangoAPP", "0013_empleados_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleados",
            name="user",
        ),
        migrations.AddField(
            model_name="empleados",
            name="Id_vivero",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mangoAPP.viveros",
            ),
            preserve_default=False,
        ),
    ]
