# Generated by Django 4.2.4 on 2023-09-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangoAPP", "0016_remove_empleados_username_empleados_username_emple"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registros_enfermedad",
            fields=[
                ("Id_reg_enfer", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_planta", models.CharField(max_length=100)),
                ("nombre_enfer", models.CharField(max_length=100)),
                ("fase", models.CharField(max_length=3)),
                ("imagen", models.TextField()),
            ],
        ),
    ]
